### ISSUE TITLE
Option to count new line for 2 chars?

### ISSUE THREAD

**Issue by Lionel09** [ractoon/jQuery-Text-Counter#13]
The plugin seems to count a new line for 2 chars but soustract only one in the display (if the "countDown" option is set to true). As I've set the "stopInputAtMaximum" option to true, the result is that the user can't type any more text but the message shows that he can type more.

**Comment by Lionel09** [comment]
In fact, my problem was server side, a new line counts for 2 chars in the server length validator. Is it possible to add an option to count 2 chars for a new line?

**Comment by Lionel09** [comment]
Alright, after new searches, it seems that new lines were encoded with "\r\n", not only "\n", that's why it was counted twice in server side.

In summary, nothing to do with this excellent plugin, sorry for disturbing!

**Comment by ractoon** [comment]
@Lionel09 Hey, thanks for the update!

No problem at all, was just having problem replicating. This makes sense though so I may need to look into something to detect these instances.
