### ISSUE TITLE
Doesn't work with TinyMCE

### ISSUE THREAD

**Issue by invalidusernam3** [ractoon/jQuery-Text-Counter#14]
Doesn't work with TinyMCE (https://www.tinymce.com)

Here's a rather hacky fix:

 - Add a hidden textarea
 - Apply text counter to the hidden textarea
 - Add to you TinyMCE:
```
setup : function(ed)	{			
	ed.on('keyup', function(e) {
		var content = tinyMCE.activeEditor.getContent({format : 'text'});
		$(".hidden-mce").val(content).change();
	});
}
```

**Comment by ractoon** [comment]
Unfortunately I'm not too familiar with how TinyMCE works. Is there a method available to detect TinyMCE enabled inputs somehow? Or apply additional callback on TinyMCE instances?

It seems like your solution may be a good one in this case if customization has to be done through TinyMCE config.

**Comment by invalidusernam3** [comment]
TinyMCE does some weird stuff, it actually doesn't use the original text input, it dynamically creates an iframe with the wysiwyg interface (of which the text input isn't actually an HTML input that could be attached to)

**Comment by ractoon** [comment]
Ahh, it sounds like your solution above may be the only route then unless someone else chimes in with a method to hook in to TinyMCE instances. I'll close this for now but if you discover anything down the road please come back and I'll take another look.
