### ISSUE TITLE
position before 

### ISSUE THREAD

**Issue by ami44** [ractoon/jQuery-Text-Counter#15]
Hello
How position message "before" a long textarea  (nobody see after textarea).
Thanks 
Ami

**Comment by ractoon** [comment]
Hi @ami44,

The easiest way may be to add a wrapper around the textarea and position the counter using CSS. I've created an example at: http://jsfiddle.net/ractoon/kajz7k1q/ but let me know if you had any questions.

**Comment by ami44** [comment]
Thank for your help
Ami44
