### ISSUE TITLE
multiple instances of JQuery Text counter in a form

### ISSUE THREAD

**Issue by HalRau** [ractoon/jQuery-Text-Counter#17]
Is it possible to have multiple instances of the text counter with different maximum word counts on a form with multiple text areas? If so, how would I do that?  I have 8 text areas on one form that need word limits.

**Comment by ractoon** [comment]
Hi @HalRau,

Yep, should should be able to do this if you assign a unique identifier on the textareas.

For example if you add a class to each textarea so they appear like:

`
<textarea class="counter-1"></textarea>
<textarea class="counter-2"></textarea>
<textarea class="counter-3"></textarea>
`

Then in your JavaScript you would have a separate counter for each of those classes like:

`
$('.counter-1').textcounter({
    min: 5,
    max: 15,
    maxcount: function(eL) { console.log('max reached' ); },
    mincount: function(el) { console.log('min reached' ); },
});

$('.counter-2').textcounter({
    type: "word",
    min : 0,
    max: 100,
    countDown: true,
    countDownText: "Words Remaining: ",
    stopInputAtMaximum: false
});

$('.counter-3').textcounter({
    min : 0,
    max: 100,
    countDown: true,
    countDownText: "Characters Remaining: ",
    stopInputAtMaximum: false
});
`
