### ISSUE TITLE
wysiwyg editor compatibility

### ISSUE THREAD

**Issue by HalRau** [ractoon/jQuery-Text-Counter#18]
I would like to use your jQuery text counter with a WYSIWYG text editor in a textarea. Is there an editor you recommend that is compatible with your word counter. I need it to be able to paste from MS Word.
Thanks

**Comment by ractoon** [comment]
Hi @HalRau,

Unfortunately I haven't tested the counter with any particular WYSIWYG editors. Theoretically it should work as long as the input/textarea is available for JavaScript events.

The only WYSIWYG editor I have used separately though is [TinyMCE](https://www.tinymce.com/), which appears to have support for similar functionality with a bit of custom code: http://www.aspsnippets.com/Articles/Character-Count-and-Character-Limit-validation-for-TinyMCE-editor-using-JavaScript.aspx

Sorry I could not be of more help, best of luck!
