### ISSUE TITLE
$base used instead of base, causes error path to fail

### ISSUE THREAD

**Issue by dtipson** [ractoon/jQuery-Text-Counter#21]
I think this is just a typo, but the base.setErrors on line 165 references $base instead of base, which causes an error (when there's an error).  I think it's meant to be just "base" though when I did that, it caused another error so not sure I have a working PR to file yet.  errorText is also not initialized as a variable in that block, causing problems in a strict/bundled environment about it not being strictly defined.

**Comment by ractoon** [comment]
Got it - I've pushed an update that appears to fix during testing but if you could confirm as well with the new version 0.4.1. Thanks for the heads up!
