### ISSUE TITLE
Add position option for counterText

### ISSUE THREAD

**Issue by Log1x** [ractoon/jQuery-Text-Counter#22]
Hi. Would it be possible to add a position option for the counter text so I don't have to force move it with a `float` in CSS?

## Example

```
$('.comments textarea').textcounter({
  counterText: ' characters',
  counterPosition: 'after'
});
```

would make it read `0 characters` instead of `Total Count: 0`.

Thanks in advance!

**Comment by ractoon** [comment]
Sure thing, that's a good idea. In 0.5.0 (latest release) the parameters `counterText` and `countDownText` have been modified to include a `%d` replaceable string.

So for your code it would look like:

```
$('.comments textarea').textcounter({
  counterText: '%d characters'
});
```

Hope that helps!

**Comment by Log1x** [comment]
Perfect! Thanks a lot for adding `minunder` and `maxunder` as well, that was going to be my next request.

Thanks a ton!
