### ISSUE TITLE
New version not working

### ISSUE THREAD

**Issue by modulexcite** [ractoon/jQuery-Text-Counter#23]
Thank you for the plugin.
The example on [jsfiddle](http://jsfiddle.net/ractoon/1xkuyp46/1/) no longer works with the new version, it seems like there is a problem with counting down text.

**Comment by ractoon** [comment]
Thanks for the heads up! Looks like my link was incorrect for this example, it should be going to: http://jsfiddle.net/ractoon/1xkuyp46/

Let me know if the updated link still wasn't working for you though.

**Comment by modulexcite** [comment]
The new link works, thanks.
