### ISSUE TITLE
Line Breaks Counting

### ISSUE THREAD

**Issue by Webtransformer** [ractoon/jQuery-Text-Counter#25]
Is there an easy way to count line breaks as 2 characters?
I checked the unminified version but could´t find the right spot to make custom changes.

Thank you!

**Comment by ractoon** [comment]
Hi @Webtransformer, 

Just released an update (version 0.6.0) that includes an option `twoCharCarriageReturn` that implements this behavior. If you ran into any troubles though let me know.

**Comment by Webtransformer** [comment]
Thank you!  :-)
