### ISSUE TITLE
Word countdown incorrect

### ISSUE THREAD

**Issue by Techywarrior** [ractoon/jQuery-Text-Counter#26]
When you set the type to Word and use the countdown it shows 1 remaining but after typing a space to then start to type the last word it prevents you from typing the last word and shows 1 remaining again.

Config used:

$(".sample").textcounter({ 
            type: "word", 
            stopInputAtMaximum: true, 
            countDown: true, 
            countDownText: "Words Remaining: %d", 
            max: 250
}); 

If you enter 249 words it will show 1 remaining. You then press "space" (which it allows) and as soon as you type a character it will delete the character(s) typed along with the space and display Words Remaining: 1 again.

**Comment by ractoon** [comment]
Hey, thanks for reporting this. Believe it should now be fixed in version 0.6.1 but let me know if you continued to run into any issues.
