### ISSUE TITLE
Incorrect text count for new line 

### ISSUE THREAD

**Issue by diptopol** [ractoon/jQuery-Text-Counter#27]
If `stopInputAtMaximum` is set true and we try to insert more character than max limit, plugin will trim the text. For `twoCharCarriageReturn` option true, if we add a newline which exceeds max limit, plugin will trim but total text count do not decrease by 2.

**Comment by diptopol** [comment]
I have created a pull request for the bugfix. If anybody has any concern, let me know.

**Comment by ractoon** [comment]
Hi @diptopol - thanks for catching this, as well as the pull request! It has been merged.
