### ISSUE TITLE
Issue with trimmed text length calculation

### ISSUE THREAD

**Issue by diptopol** [ractoon/jQuery-Text-Counter#30]
If  stopInputAtMaximum option is true and twoCharCarriageReturn option is true, trimmed text calculation does not consider twoCharCarriageReturn value. As a result, if text contains new lines, user will able to insert extra characters after reaching the max value.

Added a pull request. https://github.com/ractoon/jQuery-Text-Counter/pull/29

**Comment by ractoon** [comment]
Hi @diptopol, thanks! This pull request has been merged.
