### ISSUE TITLE
Issue in text count for countSpaces false option

### ISSUE THREAD

**Issue by diptopol** [ractoon/jQuery-Text-Counter#31]
For countSpaces false option, plugin will detect number of space based on regex. But the regex will match   a space, a tab, a line break, or a form feed. So there will be no text count increase if user insert a new line in text area. I am not sure whether the regex check is intentional or not. In my opinion this issue should be fixed. I have done the code to fix the issue. But I want to know everyone's thought on that.

**Comment by ractoon** [comment]
HI @diptopol, it does seem like the current method could be a bit greedy matching all whitespaces for some use cases. 

It may be useful to have a flag like `countWhitespaceAsSpace` that uses the current regex, and if set to false does not count tabs, line breaks, or form feeds.

**Comment by diptopol** [comment]
Hi, @ractoon do you in the favor of updating the current option countSpaces to countWhitespaceAsSpace or creating a option as countWhitespaceAsSpace. My proposal is to keep the countSpaces as it is but add the missing linefeed and form-feed count later (for countSpace false option). IMO for countSpaces false option space or tab should not be considered but line feed or form-feed should reflect according to twoCharCarraigeReturn option. Do you agree?

**Comment by ractoon** [comment]
Hi @diptopol, thanks for the feedback. I was thinking `countWhitespaceAsSpace` would be a separate option to prevent user confusion of what the options are doing.

This way if `countSpaces: false` and they have set `countWhitespaceAsSpace: true` they know that spaces (and whitespaces) are not being counted. Or if they indicate `countSpaces: true` but set `countWhitespaceAsSpace: false` then they know they're counting spaces, but not any other whitespace elements.

The goal with this set up is that users have the ability to determine what they want to count, and it's clear what is being counted at any given time to maximize their flexibility and use cases.
