### ISSUE TITLE
countExtendedCharacters not counted properly

### ISSUE THREAD

**Issue by tank-007** [ractoon/jQuery-Text-Counter#33]
if you set countExtendedCharacters to true, and set max: 10.
It allow you to enter non-english (Chinese) content greater than max 10 specified.

**Comment by ractoon** [comment]
Hi @tank-007,

There was an error with the maximum text condition address in pull request #34 and merged into version 0.6.4. If, after updating, this error persists could you provide a https://jsfiddle.net/ (or similar) demo that I can test?
