### ISSUE TITLE
Execute after Keyup event?

### ISSUE THREAD

**Issue by seanvree** [ractoon/jQuery-Text-Counter#42]
is there any way to make this work without the "live" option?  In other words - if I only wanted to count the number of occurrences AFTER I used a selector like a search button? 

Thanks!

**Comment by ractoon** [comment]
Hi @seanvree,

This may be doable if you modify the code on line 42 in the `textcounter.js` file while currently reads:

`base.$el.bind('keyup.textcounter click.textcounter blur.textcounter focus.textcounter change.textcounter paste.textcounter', base.checkLimits).trigger('click.textcounter');`

To listen for a click event on your search button instead.

**Comment by seanvree** [comment]
@ractoon  Thanks!
