### ISSUE TITLE
It will be good practice to pass more params to the overflowText var.

### ISSUE THREAD

**Issue by david1993** [ractoon/jQuery-Text-Counter#43]
I need to use in the overflowText length of all text. Can you pass more params to the text?
https://github.com/ractoon/jQuery-Text-Counter/blob/c89ff022c51b30111d441b24921974a704378a0c/textcounter.js#L279

**Comment by ractoon** [comment]
Hi @david1993,

Could you provide an example of what you're looking to do?

**Comment by ractoon** [comment]
Closed due to inactivity.
