### ISSUE TITLE
Disable/Enable buttons

### ISSUE THREAD

**Issue by u101440** [ractoon/jQuery-Text-Counter#46]
Hi guys, love the code here but very newb question here. Is there a way to disable a button when the textarea text/word count goes over the maximum or re-enable it when it's under the text/word count?

I can easily do this using ('#UpdateButton').prop('disabled', true); in my code but not whilst using your text counter.

As I say, newb question here.

Cheers

**Comment by ractoon** [comment]
You may have already solved this, but you can use the events for `maxcount` and `maxunder`.

So it might look something like:

```
$('input').textcounter({
  max: 20,
  maxcount: function(el) {
    $('#UpdateButton').prop('disabled', true);
  },
  maxunder: function(el) {
    $('#UpdateButton').prop('disabled', false);
  }
});
```
