### ISSUE TITLE
Double Counters

### ISSUE THREAD

**Issue by jfine24** [ractoon/jQuery-Text-Counter#50]
Is there any reason why I got double counters under one input element?

**Comment by jfine24** [comment]
I figured you need to see some of my scripts.  Here they are:

**script.js**
`    $(".comment-counter").textcounter({
        type: "character", 
        max: 50,
        countDown: true,
        countDownText: "Characters Remaining: %d"
    });
`
**index.cshtml**
` <div class="md-form ml-5 mr-5 mb-4" id="comment-div">
    <i class="fas fa-lock prefix grey-text"></i>
    <label data-error="wrong" data-success="right" for="newComment">Comment</label>
    <input type="text" id="newComment" name="newComment" class="form-control validate comment-counter" maxlength="50" title="Comment: 50 characters remaining">
 </div>
`

**Comment by ractoon** [comment]
I can't seem to reproduce this. Are you able to create a fiddle (could fork the base case at http://jsfiddle.net/ractoon/p7x72La3/) that shows this issue?

Thanks!
