### ISSUE TITLE
Update text-count-message div to aria-label="polite" instead of assertive

### ISSUE THREAD

**Issue by ameshkin** [ractoon/jQuery-Text-Counter#52]
hello there,

Your text counter is widely used so we thought we would ask you to update the code base regarding `aria-label="assertive"`

placed on the `text-count-message` div character count. Our users feel as if this should be set to `polite`.  We wanted to first ask you to perhaps make this change, before forking your repo.  It is very annoying that the character count is repeated as a blind user types.

https://github.com/search?q=repo%3Aractoon%2FjQuery-Text-Counter+assertive+live&type=code

**Comment by ractoon** [comment]
That makes sense to me. Thank you for your PR!
