### ISSUE TITLE
Not showing count for Chinese words

### ISSUE THREAD

**Issue by anieshjoseph** [ractoon/jQuery-Text-Counter#8]
I have used this plugin and works great for English words. But it doesn't work for Chinese words even I set "countExtendedCharacters " to true. 

$('#description').textcounter({
    max: 200,
    countDownText: "Characters Left: ",
    countExtendedCharacters  : true,
    type                     : "word",
});

**Comment by ractoon** [comment]
Could you share the full page code, along with the text you're inputting? I attempted to reproduce this issue but could not with the test I was using.

**Comment by anieshjoseph** [comment]
I have downloaded latest js file and it is now working perfectly for Chinese letters.
